
[development]
[development.database]
db ="../data/subscription"

[containerized]
[containerized.database]
db ="../data/subscription"



# From root of project. See utils/aliases.py
[misc]
migration_directory="/migrations"