version: "3"

services:
  
  gateway:
    build: ./gateway 
    container_name: si-exam-gateway
    ports: 20090:20090
    networks:
      - app-network 


networks:
  app-network:
    driver: "bridge"


# Primarily only includes technologies vital to development
