# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: song.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='song.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\017Metadata.Protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nsong.proto\"J\n\x11\x43reateSongRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x14\n\x0c\x64uration_sec\x18\x02 \x01(\x05\x12\x10\n\x08vinyl_id\x18\x03 \x01(\t\"0\n\x12\x43reateSongResponse\x12\x1a\n\x04song\x18\x01 \x01(\x0b\x32\x0c.SongMessage\" \n\x12GetSongByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"X\n\x13GetSongByIdResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x14\n\x0c\x64uration_sec\x18\x03 \x01(\x05\x12\x10\n\x08vinyl_id\x18\x04 \x01(\t\"V\n\x11UpdateSongRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x14\n\x0c\x64uration_sec\x18\x03 \x01(\x05\x12\x10\n\x08vinyl_id\x18\x04 \x01(\t\"+\n\x12UpdateSongResponse\x12\x15\n\rstatusMessage\x18\x01 \x01(\t\"#\n\x15\x44\x65leteSongByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"/\n\x16\x44\x65leteSongByIdResponse\x12\x15\n\rstatusMessage\x18\x01 \x01(\t\"\x14\n\x12GetAllSongsRequest\"2\n\x13GetAllSongsResponse\x12\x1b\n\x05songs\x18\x01 \x03(\x0b\x32\x0c.SongMessage\"P\n\x0bSongMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x14\n\x0c\x64uration_sec\x18\x03 \x01(\x05\x12\x10\n\x08vinyl_id\x18\x04 \x01(\t2\xb5\x02\n\x04Song\x12\x37\n\ncreateSong\x12\x12.CreateSongRequest\x1a\x13.CreateSongResponse\"\x00\x12:\n\x0bgetSongById\x12\x13.GetSongByIdRequest\x1a\x14.GetSongByIdResponse\"\x00\x12\x37\n\nupdateSong\x12\x12.UpdateSongRequest\x1a\x13.UpdateSongResponse\"\x00\x12\x43\n\x0e\x64\x65leteSongById\x12\x16.DeleteSongByIdRequest\x1a\x17.DeleteSongByIdResponse\"\x00\x12:\n\x0bgetAllSongs\x12\x13.GetAllSongsRequest\x1a\x14.GetAllSongsResponse\"\x00\x42\x12\xaa\x02\x0fMetadata.Protosb\x06proto3'
)




_CREATESONGREQUEST = _descriptor.Descriptor(
  name='CreateSongRequest',
  full_name='CreateSongRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='CreateSongRequest.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration_sec', full_name='CreateSongRequest.duration_sec', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vinyl_id', full_name='CreateSongRequest.vinyl_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=88,
)


_CREATESONGRESPONSE = _descriptor.Descriptor(
  name='CreateSongResponse',
  full_name='CreateSongResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='song', full_name='CreateSongResponse.song', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=138,
)


_GETSONGBYIDREQUEST = _descriptor.Descriptor(
  name='GetSongByIdRequest',
  full_name='GetSongByIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GetSongByIdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=172,
)


_GETSONGBYIDRESPONSE = _descriptor.Descriptor(
  name='GetSongByIdResponse',
  full_name='GetSongByIdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GetSongByIdResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='GetSongByIdResponse.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration_sec', full_name='GetSongByIdResponse.duration_sec', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vinyl_id', full_name='GetSongByIdResponse.vinyl_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=262,
)


_UPDATESONGREQUEST = _descriptor.Descriptor(
  name='UpdateSongRequest',
  full_name='UpdateSongRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UpdateSongRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='UpdateSongRequest.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration_sec', full_name='UpdateSongRequest.duration_sec', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vinyl_id', full_name='UpdateSongRequest.vinyl_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=350,
)


_UPDATESONGRESPONSE = _descriptor.Descriptor(
  name='UpdateSongResponse',
  full_name='UpdateSongResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='statusMessage', full_name='UpdateSongResponse.statusMessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=395,
)


_DELETESONGBYIDREQUEST = _descriptor.Descriptor(
  name='DeleteSongByIdRequest',
  full_name='DeleteSongByIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DeleteSongByIdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=432,
)


_DELETESONGBYIDRESPONSE = _descriptor.Descriptor(
  name='DeleteSongByIdResponse',
  full_name='DeleteSongByIdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='statusMessage', full_name='DeleteSongByIdResponse.statusMessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=481,
)


_GETALLSONGSREQUEST = _descriptor.Descriptor(
  name='GetAllSongsRequest',
  full_name='GetAllSongsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=483,
  serialized_end=503,
)


_GETALLSONGSRESPONSE = _descriptor.Descriptor(
  name='GetAllSongsResponse',
  full_name='GetAllSongsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='songs', full_name='GetAllSongsResponse.songs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=505,
  serialized_end=555,
)


_SONGMESSAGE = _descriptor.Descriptor(
  name='SongMessage',
  full_name='SongMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SongMessage.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='SongMessage.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration_sec', full_name='SongMessage.duration_sec', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vinyl_id', full_name='SongMessage.vinyl_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=557,
  serialized_end=637,
)

_CREATESONGRESPONSE.fields_by_name['song'].message_type = _SONGMESSAGE
_GETALLSONGSRESPONSE.fields_by_name['songs'].message_type = _SONGMESSAGE
DESCRIPTOR.message_types_by_name['CreateSongRequest'] = _CREATESONGREQUEST
DESCRIPTOR.message_types_by_name['CreateSongResponse'] = _CREATESONGRESPONSE
DESCRIPTOR.message_types_by_name['GetSongByIdRequest'] = _GETSONGBYIDREQUEST
DESCRIPTOR.message_types_by_name['GetSongByIdResponse'] = _GETSONGBYIDRESPONSE
DESCRIPTOR.message_types_by_name['UpdateSongRequest'] = _UPDATESONGREQUEST
DESCRIPTOR.message_types_by_name['UpdateSongResponse'] = _UPDATESONGRESPONSE
DESCRIPTOR.message_types_by_name['DeleteSongByIdRequest'] = _DELETESONGBYIDREQUEST
DESCRIPTOR.message_types_by_name['DeleteSongByIdResponse'] = _DELETESONGBYIDRESPONSE
DESCRIPTOR.message_types_by_name['GetAllSongsRequest'] = _GETALLSONGSREQUEST
DESCRIPTOR.message_types_by_name['GetAllSongsResponse'] = _GETALLSONGSRESPONSE
DESCRIPTOR.message_types_by_name['SongMessage'] = _SONGMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateSongRequest = _reflection.GeneratedProtocolMessageType('CreateSongRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATESONGREQUEST,
  '__module__' : 'song_pb2'
  # @@protoc_insertion_point(class_scope:CreateSongRequest)
  })
_sym_db.RegisterMessage(CreateSongRequest)

CreateSongResponse = _reflection.GeneratedProtocolMessageType('CreateSongResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATESONGRESPONSE,
  '__module__' : 'song_pb2'
  # @@protoc_insertion_point(class_scope:CreateSongResponse)
  })
_sym_db.RegisterMessage(CreateSongResponse)

GetSongByIdRequest = _reflection.GeneratedProtocolMessageType('GetSongByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSONGBYIDREQUEST,
  '__module__' : 'song_pb2'
  # @@protoc_insertion_point(class_scope:GetSongByIdRequest)
  })
_sym_db.RegisterMessage(GetSongByIdRequest)

GetSongByIdResponse = _reflection.GeneratedProtocolMessageType('GetSongByIdResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSONGBYIDRESPONSE,
  '__module__' : 'song_pb2'
  # @@protoc_insertion_point(class_scope:GetSongByIdResponse)
  })
_sym_db.RegisterMessage(GetSongByIdResponse)

UpdateSongRequest = _reflection.GeneratedProtocolMessageType('UpdateSongRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESONGREQUEST,
  '__module__' : 'song_pb2'
  # @@protoc_insertion_point(class_scope:UpdateSongRequest)
  })
_sym_db.RegisterMessage(UpdateSongRequest)

UpdateSongResponse = _reflection.GeneratedProtocolMessageType('UpdateSongResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESONGRESPONSE,
  '__module__' : 'song_pb2'
  # @@protoc_insertion_point(class_scope:UpdateSongResponse)
  })
_sym_db.RegisterMessage(UpdateSongResponse)

DeleteSongByIdRequest = _reflection.GeneratedProtocolMessageType('DeleteSongByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETESONGBYIDREQUEST,
  '__module__' : 'song_pb2'
  # @@protoc_insertion_point(class_scope:DeleteSongByIdRequest)
  })
_sym_db.RegisterMessage(DeleteSongByIdRequest)

DeleteSongByIdResponse = _reflection.GeneratedProtocolMessageType('DeleteSongByIdResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETESONGBYIDRESPONSE,
  '__module__' : 'song_pb2'
  # @@protoc_insertion_point(class_scope:DeleteSongByIdResponse)
  })
_sym_db.RegisterMessage(DeleteSongByIdResponse)

GetAllSongsRequest = _reflection.GeneratedProtocolMessageType('GetAllSongsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETALLSONGSREQUEST,
  '__module__' : 'song_pb2'
  # @@protoc_insertion_point(class_scope:GetAllSongsRequest)
  })
_sym_db.RegisterMessage(GetAllSongsRequest)

GetAllSongsResponse = _reflection.GeneratedProtocolMessageType('GetAllSongsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETALLSONGSRESPONSE,
  '__module__' : 'song_pb2'
  # @@protoc_insertion_point(class_scope:GetAllSongsResponse)
  })
_sym_db.RegisterMessage(GetAllSongsResponse)

SongMessage = _reflection.GeneratedProtocolMessageType('SongMessage', (_message.Message,), {
  'DESCRIPTOR' : _SONGMESSAGE,
  '__module__' : 'song_pb2'
  # @@protoc_insertion_point(class_scope:SongMessage)
  })
_sym_db.RegisterMessage(SongMessage)


DESCRIPTOR._options = None

_SONG = _descriptor.ServiceDescriptor(
  name='Song',
  full_name='Song',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=640,
  serialized_end=949,
  methods=[
  _descriptor.MethodDescriptor(
    name='createSong',
    full_name='Song.createSong',
    index=0,
    containing_service=None,
    input_type=_CREATESONGREQUEST,
    output_type=_CREATESONGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getSongById',
    full_name='Song.getSongById',
    index=1,
    containing_service=None,
    input_type=_GETSONGBYIDREQUEST,
    output_type=_GETSONGBYIDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='updateSong',
    full_name='Song.updateSong',
    index=2,
    containing_service=None,
    input_type=_UPDATESONGREQUEST,
    output_type=_UPDATESONGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='deleteSongById',
    full_name='Song.deleteSongById',
    index=3,
    containing_service=None,
    input_type=_DELETESONGBYIDREQUEST,
    output_type=_DELETESONGBYIDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getAllSongs',
    full_name='Song.getAllSongs',
    index=4,
    containing_service=None,
    input_type=_GETALLSONGSREQUEST,
    output_type=_GETALLSONGSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SONG)

DESCRIPTOR.services_by_name['Song'] = _SONG

# @@protoc_insertion_point(module_scope)
