
[development]
[development.server]
host = "127.0.0.1"
port = 20090


[development.clients]
[development.clients.warehouse]
host = "127.0.0.1"
port = 20080


[development.clients.metadata]
host = "127.0.0.1"
port = 20070


[development.clients.subscription]
host = "127.0.0.1"
port = 20060

[development.clients.reservation]
host = "127.0.0.1"
port = 20050


[production]
[production.server]
host = "0.0.0.0"
port = 20090


[production.clients]
[production.clients.warehouse]
host = "warehouse-service"
port = 20080


[production.clients.metadata]
host = "metadata-service"
port = 20070


[production.clients.subscription]
host = "subscription-service"
port = 20060

[production.clients.reservation]
host = "reservation-service"
port = 5000

[production.clients.restock]
host = "restock-service"
port = 6000
