[development]
[development.server]
host="127.0.0.1"
port=20060
max_workers=10

[development.kafka]
broker="localhost:9094"

[development.database]
path=""
name="subscription"

[production]
[production.server]
host="0.0.0.0"
port=20060
max_workers=10

[production.kafka]
broker="kafka-service:9092"

[production.database]
path=""
name="subscription"
