CREATE TABLE IF NOT EXISTS subscription(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    is_active BOOL NOT NULL,
    expiration_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
