apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata
spec:
  selector:
    matchLabels:
      app: metadata
  template:
    metadata:
      labels:
        app: metadata
    spec:
      volumes:
      - name: metadatadb
        hostPath:
          path: /srv/db/metadata
          type: DirectoryOrCreate
      containers:
      - name: metadata
        image: ghcr.io/system-integration-exam/si-exam/metadata-service:latest
        volumeMounts:
        - name: metadatadb
          mountPath: /app/src/data
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 20070

---

apiVersion: v1
kind: Service
metadata:
  name: metadata-service
spec:
  selector:
    app: metadata
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 20070