apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
spec:
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
      - name: reservation
        image: ghcr.io/system-integration-exam/si-exam/reservation-service:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: reservation-service
spec:
  selector:
    app: reservation
  type: ClusterIP
  ports:
  - port: 5000
