apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse
spec:
  selector:
    matchLabels:
      app: warehouse
  template:
    metadata:
      labels:
        app: warehouse
    spec:
      containers:
      - name: warehouse
        image: ghcr.io/system-integration-exam/si-exam/warehouse-service:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 20080

---

apiVersion: v1
kind: Service
metadata:
  name: warehouse-service
spec:
  selector:
    app: warehouse
  type: ClusterIP
  ports:
  - port: 20080
  env:
  - name: PRODUCTION
  value: "true"
