# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/song.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/song.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11protos/song.proto\"\x19\n\x0bSongRequest\x12\n\n\x02id\x18\x01 \x01(\t\"?\n\x0cSongResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x14\n\x0c\x64uration_sec\x18\x03 \x01(\x05\x32\x32\n\x04Song\x12*\n\x0bgetSongInfo\x12\x0c.SongRequest\x1a\r.SongResponseb\x06proto3'
)




_SONGREQUEST = _descriptor.Descriptor(
  name='SongRequest',
  full_name='SongRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SongRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=46,
)


_SONGRESPONSE = _descriptor.Descriptor(
  name='SongResponse',
  full_name='SongResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SongResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='SongResponse.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration_sec', full_name='SongResponse.duration_sec', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['SongRequest'] = _SONGREQUEST
DESCRIPTOR.message_types_by_name['SongResponse'] = _SONGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SongRequest = _reflection.GeneratedProtocolMessageType('SongRequest', (_message.Message,), {
  'DESCRIPTOR' : _SONGREQUEST,
  '__module__' : 'protos.song_pb2'
  # @@protoc_insertion_point(class_scope:SongRequest)
  })
_sym_db.RegisterMessage(SongRequest)

SongResponse = _reflection.GeneratedProtocolMessageType('SongResponse', (_message.Message,), {
  'DESCRIPTOR' : _SONGRESPONSE,
  '__module__' : 'protos.song_pb2'
  # @@protoc_insertion_point(class_scope:SongResponse)
  })
_sym_db.RegisterMessage(SongResponse)



_SONG = _descriptor.ServiceDescriptor(
  name='Song',
  full_name='Song',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=113,
  serialized_end=163,
  methods=[
  _descriptor.MethodDescriptor(
    name='getSongInfo',
    full_name='Song.getSongInfo',
    index=0,
    containing_service=None,
    input_type=_SONGREQUEST,
    output_type=_SONGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SONG)

DESCRIPTOR.services_by_name['Song'] = _SONG

# @@protoc_insertion_point(module_scope)
