name: Template for building and publishing a docker images

on: 
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_path:
        required: true
        type: string
    secrets:
      ghcr_token:
        required: true

jobs:
  build_and_publish_image:
    name: Build and push docker image to GitHub container registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Release Version and Lowercase Repo
        run: |
          echo "RELEASE_VERSION=$(echo ${GITHUB_SHA} | head -c 8)" >> $GITHUB_ENV &&
          echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Login to GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ghcr_token }}

      - name: Create Digest and Existing flag
        run: |
          echo "EXISTING=0" >> $GITHUB_ENV &&
          echo "DIGEST=$(sha256sum <(find ./${{ inputs.image_path }}/. -type f -exec sha256sum {} \; | sort) | head -c 12)" >> $GITHUB_ENV
      
      - name: Check Docker if Digest already Existing
        run: |
          docker manifest inspect ghcr.io/${{ env.REPO }}/${{ inputs.image_name }}:sha256-${{ env.DIGEST }} > /dev/null || echo "EXISTING=$?" >> $GITHUB_ENV &&
          echo $EXISTING

      - name: Build and push Docker image
        if: env.EXISTING == 1
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ inputs.image_path }}
          tags: |
            ghcr.io/${{ env.REPO }}/${{ inputs.image_name }}:git-${{ env.RELEASE_VERSION }}
            ghcr.io/${{ env.REPO }}/${{ inputs.image_name }}:sha256-${{ env.DIGEST }}
            ghcr.io/${{ env.REPO }}/${{ inputs.image_name }}:latest
