
[development]
[development.database]
db ="data/store"

[containerized]
[containerized.database]
db ="data/store"



# From root of project. See utils/aliases.py
[misc]
migration_directory="/migrations"